"""Initial schema

Revision ID: 25c9ab64045b
Revises: 
Create Date: 2026-07-17 19:37:42.629601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c9ab64045b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabla_drones',
    sa.Column('id_drone', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('ultima_revision', sa.String(length=50), nullable=True),
    sa.Column('horas_vuelo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_drone')
    )
    op.create_table('tabla_servicios',
    sa.Column('id_servicio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_servicio', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_base_m2', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_table('tabla_usuarios',
    sa.Column('id_usuarios', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('fecha_de_creacion', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuarios'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tabla_clientes',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellido_1', sa.String(length=30), nullable=False),
    sa.Column('apellido_2', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=True),
    sa.Column('ciudad_expedicion', sa.String(length=50), nullable=True),
    sa.Column('fecha_expedicion', sa.String(length=30), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['tabla_usuarios.id_usuarios'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('tabla_mantenimientos_flota',
    sa.Column('id_mantenimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_drone', sa.Integer(), nullable=False),
    sa.Column('tipo_mantenimiento', sa.String(length=50), nullable=False),
    sa.Column('descripcion_falla', sa.Text(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=True),
    sa.Column('costo_mantenimiento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('responsable_tecnico', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_drone'], ['tabla_drones.id_drone'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_mantenimiento')
    )
    op.create_table('tabla_notificaciones',
    sa.Column('id_notificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['tabla_usuarios.id_usuarios'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('tecnicos',
    sa.Column('id_tecnico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido_1', sa.String(length=50), nullable=False),
    sa.Column('apellido_2', sa.String(length=50), nullable=True),
    sa.Column('certificacion', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('servicios_capacitados', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['tabla_usuarios.id_usuarios'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_tecnico')
    )
    op.create_table('tabla_fincas',
    sa.Column('id_finca', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre_finca', sa.String(length=50), nullable=False),
    sa.Column('ubicacion_municipio', sa.String(length=50), nullable=True),
    sa.Column('hectareas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['tabla_clientes.id_cliente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_finca')
    )
    op.create_table('tabla_agenda',
    sa.Column('id_turno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_finca', sa.Integer(), nullable=True),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('id_drone', sa.Integer(), nullable=True),
    sa.Column('id_tecnico', sa.Integer(), nullable=True),
    sa.Column('fecha_de_turno', sa.Date(), nullable=False),
    sa.Column('hora_inicio_estimada', sa.Time(), nullable=False),
    sa.Column('hora_fin_estimada', sa.Time(), nullable=True),
    sa.Column('tipo_turno', sa.Enum('Asesoria', 'Mantenimiento', 'Fumigacion', 'Monitoreo', name='tipoturnoenum'), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('tarifa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_logistico', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cel', sa.String(length=20), nullable=True),
    sa.Column('observaciones_servicio', sa.Text(), nullable=True),
    sa.Column('hora_inicio_real', sa.Time(), nullable=True),
    sa.Column('hora_fin_real', sa.Time(), nullable=True),
    sa.Column('retraso_justificacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_drone'], ['tabla_drones.id_drone'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_finca'], ['tabla_fincas.id_finca'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['tabla_servicios.id_servicio'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tecnico'], ['tecnicos.id_tecnico'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_turno')
    )
    op.create_table('tabla_entregables',
    sa.Column('id_entregable', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=50), nullable=False),
    sa.Column('url_archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_turno'], ['tabla_agenda.id_turno'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_entregable')
    )
    op.create_table('tabla_pagos',
    sa.Column('id_pago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('metodo_pago', sa.Enum('Efectivo', 'Transferencia', 'Tarjeta', 'Pendiente', name='metodopagoenum'), nullable=True),
    sa.Column('referencia_transaccion', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_turno'], ['tabla_agenda.id_turno'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_table('tabla_reportes_vuelo',
    sa.Column('id_reporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('insumos_litros_aplicados', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('agua_litros', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('baterias_utilizadas', sa.Integer(), nullable=False),
    sa.Column('cumple_rac100', sa.Integer(), nullable=True),
    sa.Column('observaciones_campo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_turno'], ['tabla_agenda.id_turno'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reporte'),
    sa.UniqueConstraint('id_turno')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabla_reportes_vuelo')
    op.drop_table('tabla_pagos')
    op.drop_table('tabla_entregables')
    op.drop_table('tabla_agenda')
    op.drop_table('tabla_fincas')
    op.drop_table('tecnicos')
    op.drop_table('tabla_notificaciones')
    op.drop_table('tabla_mantenimientos_flota')
    op.drop_table('tabla_clientes')
    op.drop_table('tabla_usuarios')
    op.drop_table('tabla_servicios')
    op.drop_table('tabla_drones')
    # ### end Alembic commands ###
