import re

# Emojis to FontAwesome mappings
EMOJI_FA_MAP = {
    '📩': '<i class="fa-solid fa-headset"></i>',
    '🌱': '<i class="fa-solid fa-seedling"></i>',
    '🌾': '<i class="fa-solid fa-wheat-awn"></i>',
    '🌽': '<i class="fa-solid fa-wheat-awn"></i>',
    '📍': '<i class="fa-solid fa-location-dot"></i>',
    '👁️': '<i class="fa-solid fa-eye"></i>',
    '👁': '<i class="fa-solid fa-eye"></i>',
    '🔍': '<i class="fa-solid fa-magnifying-glass"></i>',
    '✏️': '<i class="fa-solid fa-pen-to-square"></i>',
    '✏': '<i class="fa-solid fa-pen-to-square"></i>',
    '🔒': '<i class="fa-solid fa-lock"></i>',
    '🔐': '<i class="fa-solid fa-lock"></i>',
    '🔑': '<i class="fa-solid fa-key"></i>',
    '📤': '<i class="fa-solid fa-cloud-arrow-up"></i>',
    '📥': '<i class="fa-solid fa-cloud-arrow-down"></i>',
    '🚁': '<i class="fa-solid fa-helicopter"></i>',
    '🧑‍💼': '<i class="fa-solid fa-user-tie"></i>',
    '👷': '<i class="fa-solid fa-user-gear"></i>',
    '👥': '<i class="fa-solid fa-users"></i>',
    '👤': '<i class="fa-solid fa-user"></i>',
    '📱': '<i class="fa-solid fa-phone"></i>',
    '📞': '<i class="fa-solid fa-phone"></i>',
    '📧': '<i class="fa-solid fa-envelope"></i>',
    '🗂️': '<i class="fa-solid fa-folder-tree"></i>',
    '⏰': '<i class="fa-solid fa-clock"></i>',
    '💬': '<i class="fa-solid fa-comment-dots"></i>',
    '🗑️': '<i class="fa-solid fa-trash-can"></i>',
    '🗑': '<i class="fa-solid fa-trash-can"></i>',
    '📅': '<i class="fa-solid fa-calendar-days"></i>',
    '🗓️': '<i class="fa-solid fa-calendar-days"></i>',
    '🗓': '<i class="fa-solid fa-calendar-days"></i>',
    '🏡': '<i class="fa-solid fa-house"></i>',
    '🏠': '<i class="fa-solid fa-house"></i>',
    '🔔': '<i class="fa-solid fa-bell"></i>',
    '🔄': '<i class="fa-solid fa-rotate"></i>',
    '🛠️': '<i class="fa-solid fa-screwdriver-wrench"></i>',
    '🛠': '<i class="fa-solid fa-screwdriver-wrench"></i>',
    '🔗': '<i class="fa-solid fa-link"></i>',
    '⚠️': '<i class="fa-solid fa-triangle-exclamation"></i>',
    '⚠': '<i class="fa-solid fa-triangle-exclamation"></i>',
    '🎉': '<i class="fa-solid fa-award"></i>',
    '💵': '<i class="fa-solid fa-money-bill-wave"></i>',
    '💰': '<i class="fa-solid fa-wallet"></i>',
    '📊': '<i class="fa-solid fa-chart-line"></i>',
    '📈': '<i class="fa-solid fa-chart-line"></i>',
    '📋': '<i class="fa-solid fa-clipboard-list"></i>',
    '📑': '<i class="fa-solid fa-file-lines"></i>',
    '📄': '<i class="fa-solid fa-file-invoice"></i>',
    '📑': '<i class="fa-solid fa-file-lines"></i>',
    '✈️': '<i class="fa-solid fa-plane"></i>'
}

print("Emoji cleaner map configured with", len(EMOJI_FA_MAP), "mappings")
